version: '2.7'
services:
  db:
    container_name: postgres_db
    image: postgres:15.4-alpine3.17
    env_file: ../.env    
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal


volumes:
  pgdata: {}


networks:
  internal: